version: "3.9"

services:
  influxdb:
    image: influxdb:1.8
    container_name: stm2-influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: stm2
      INFLUXDB_ADMIN_ENABLED: "true"
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:10.0.0
    container_name: stm2-grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning

volumes:
  influxdb-data:
  grafana-data:
